<?php
/**
 * Page content field schema: homepage and property.
 *
 * @package Restwell_Retreats
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Front page definitions.
 */
function restwell_get_front_page_field_definitions() {
	return array(
		'Hero' => array(
			'hero_heading'             => restwell_field( __( 'Hero heading (h1). Aim for five words or fewer; use Enter only if a second line is essential', 'restwell-retreats' ) ),
			'hero_subheading'          => restwell_field( __( 'Hero intro: one short sentence (shown in the hero under the headline)', 'restwell-retreats' ) ),
			'hero_media_id'            => restwell_field( __( 'Hero background (image or video)', 'restwell-retreats' ), 'media' ),
			'hero_mobile_video_id'     => restwell_field( __( 'Hero mobile video (optional attachment ID; used only when Hero background is a video)', 'restwell-retreats' ), 'media' ),
			'hero_video_poster_id'     => restwell_field( __( 'Hero video poster image (optional attachment ID; used only when Hero background is a video)', 'restwell-retreats' ), 'image' ),
			'hero_cta_primary_label'   => restwell_field( __( 'Hero primary button label', 'restwell-retreats' ) ),
			'hero_cta_primary_url'     => restwell_field( __( 'Hero primary button URL', 'restwell-retreats' ) ),
			'hero_cta_secondary_label' => restwell_field( __( 'Hero secondary button label', 'restwell-retreats' ) ),
			'hero_cta_secondary_url'   => restwell_field( __( 'Hero secondary button URL', 'restwell-retreats' ) ),
			'hero_cta_reassurance'     => restwell_field( __( 'Optional line under hero buttons (response time & no obligation). Empty = use theme default; clear the field and save to hide.', 'restwell-retreats' ), 'textarea' ),
		),
		'Partners' => array(
			'home_partners_label'    => restwell_field( __( 'Section label (optional)', 'restwell-retreats' ) ),
			'home_partners_heading'  => restwell_field( __( 'Section heading (h2). Clear and save empty to hide this strip.', 'restwell-retreats' ) ),
			'home_partners_intro'    => restwell_field( __( 'Short intro paragraph shown on the left of this strip', 'restwell-retreats' ), 'textarea' ),
			'home_partners_cta_text' => restwell_field( __( 'Journey button label', 'restwell-retreats' ) ),
			'home_partners_cta_url'  => restwell_field( __( 'Journey button URL (e.g. /how-it-works/)', 'restwell-retreats' ) ),
			'home_partner_1_name'    => restwell_field( __( 'Partner 1 name', 'restwell-retreats' ) ),
			'home_partner_1_url'     => restwell_field( __( 'Partner 1 URL', 'restwell-retreats' ) ),
			'home_partner_1_logo_id' => restwell_field( __( 'Partner 1 logo image (attachment ID)', 'restwell-retreats' ), 'image' ),
			'home_partner_2_name'    => restwell_field( __( 'Partner 2 name', 'restwell-retreats' ) ),
			'home_partner_2_url'     => restwell_field( __( 'Partner 2 URL', 'restwell-retreats' ) ),
			'home_partner_2_logo_id' => restwell_field( __( 'Partner 2 logo image (attachment ID)', 'restwell-retreats' ), 'image' ),
			'home_partner_3_name'    => restwell_field( __( 'Partner 3 name', 'restwell-retreats' ) ),
			'home_partner_3_url'     => restwell_field( __( 'Partner 3 URL', 'restwell-retreats' ) ),
			'home_partner_3_logo_id' => restwell_field( __( 'Partner 3 logo image (attachment ID)', 'restwell-retreats' ), 'image' ),
			'home_partner_4_name'    => restwell_field( __( 'Partner 4 name', 'restwell-retreats' ) ),
			'home_partner_4_url'     => restwell_field( __( 'Partner 4 URL', 'restwell-retreats' ) ),
			'home_partner_4_logo_id' => restwell_field( __( 'Partner 4 logo image (attachment ID)', 'restwell-retreats' ), 'image' ),
			'home_partner_5_name'    => restwell_field( __( 'Partner 5 name', 'restwell-retreats' ) ),
			'home_partner_5_url'     => restwell_field( __( 'Partner 5 URL', 'restwell-retreats' ) ),
			'home_partner_5_logo_id' => restwell_field( __( 'Partner 5 logo image (attachment ID)', 'restwell-retreats' ), 'image' ),
		),
		'Area & funding' => array(
			'home_teaser_label'         => restwell_field( __( 'Section label (empty = hide band)', 'restwell-retreats' ) ),
			'home_teaser_area_title'    => restwell_field( __( 'Area column title', 'restwell-retreats' ) ),
			'home_teaser_area_body'     => restwell_field( __( 'Area column body', 'restwell-retreats' ), 'textarea' ),
			'home_teaser_funding_title' => restwell_field( __( 'Funding column title', 'restwell-retreats' ) ),
			'home_teaser_funding_body'  => restwell_field( __( 'Funding column body', 'restwell-retreats' ), 'textarea' ),
		),
		'Property snapshot' => array(
			'property_label'      => restwell_field( __( 'Section label', 'restwell-retreats' ) ),
			'property_heading'    => restwell_field( __( 'Section heading (e.g. Our Whitstable home)', 'restwell-retreats' ) ),
			'property_body'       => restwell_field( __( 'Property body copy', 'restwell-retreats' ), 'textarea' ),
			'property_cta_label'  => restwell_field( __( 'CTA link label', 'restwell-retreats' ) ),
			'property_cta_url'    => restwell_field( __( 'CTA link URL', 'restwell-retreats' ) ),
			'property_image_id'   => restwell_field( __( 'Property image (attachment ID)', 'restwell-retreats' ), 'image' ),
		),
		'Comparison cards' => array(
			'home_comparison_heading' => restwell_field( __( 'Section heading (h2)', 'restwell-retreats' ) ),
			'why_item1_title'         => restwell_field( __( 'Card 1 title', 'restwell-retreats' ) ),
			'why_item1_desc'          => restwell_field( __( 'Card 1 description', 'restwell-retreats' ), 'textarea' ),
			'why_item2_title'         => restwell_field( __( 'Card 2 title', 'restwell-retreats' ) ),
			'why_item2_desc'          => restwell_field( __( 'Card 2 description', 'restwell-retreats' ), 'textarea' ),
			'why_item3_title'         => restwell_field( __( 'Card 3 title', 'restwell-retreats' ) ),
			'why_item3_desc'          => restwell_field( __( 'Card 3 description', 'restwell-retreats' ), 'textarea' ),
		),
		'Testimonials' => array(
			'testimonial_label'   => restwell_field( __( 'Section label (optional)', 'restwell-retreats' ) ),
			'testimonial_heading' => restwell_field( __( 'Section heading (e.g. What guests say)', 'restwell-retreats' ) ),
			'testimonial_1_quote' => restwell_field( __( 'Testimonial 1 quote — guest’s consecutive words from the review, unchanged', 'restwell-retreats' ), 'textarea' ),
			'testimonial_1_name'  => restwell_field( __( 'Testimonial 1 name', 'restwell-retreats' ) ),
			'testimonial_1_role'  => restwell_field( __( 'Testimonial 1 role/location (optional)', 'restwell-retreats' ) ),
			'testimonial_2_quote' => restwell_field( __( 'Testimonial 2 quote', 'restwell-retreats' ), 'textarea' ),
			'testimonial_2_name'  => restwell_field( __( 'Testimonial 2 name', 'restwell-retreats' ) ),
			'testimonial_2_role'  => restwell_field( __( 'Testimonial 2 role (optional)', 'restwell-retreats' ) ),
			'testimonial_3_quote' => restwell_field( __( 'Testimonial 3 quote', 'restwell-retreats' ), 'textarea' ),
			'testimonial_3_name'  => restwell_field( __( 'Testimonial 3 name', 'restwell-retreats' ) ),
			'testimonial_3_role'  => restwell_field( __( 'Testimonial 3 role (optional)', 'restwell-retreats' ) ),
			'testimonial_4_quote' => restwell_field( __( 'Testimonial 4 quote', 'restwell-retreats' ), 'textarea' ),
			'testimonial_4_name'  => restwell_field( __( 'Testimonial 4 name', 'restwell-retreats' ) ),
			'testimonial_4_role'  => restwell_field( __( 'Testimonial 4 role (optional)', 'restwell-retreats' ) ),
			'testimonial_5_quote' => restwell_field( __( 'Testimonial 5 quote', 'restwell-retreats' ), 'textarea' ),
			'testimonial_5_name'  => restwell_field( __( 'Testimonial 5 name', 'restwell-retreats' ) ),
			'testimonial_5_role'  => restwell_field( __( 'Testimonial 5 role (optional)', 'restwell-retreats' ) ),
		),
		'Optional care' => array(
			'home_care_label'     => restwell_field( __( 'Section label (eyebrow; empty = heading uses eyebrow style)', 'restwell-retreats' ) ),
			'home_care_heading'   => restwell_field( __( 'Section heading (h2)', 'restwell-retreats' ) ),
			'home_care_intro'     => restwell_field( __( 'Intro paragraph above the checklist', 'restwell-retreats' ), 'textarea' ),
			'home_care_item1_title' => restwell_field( __( 'Checklist item 1 title', 'restwell-retreats' ) ),
			'home_care_item1_body'  => restwell_field( __( 'Checklist item 1 body', 'restwell-retreats' ), 'textarea' ),
			'home_care_item2_title' => restwell_field( __( 'Checklist item 2 title', 'restwell-retreats' ) ),
			'home_care_item2_body'  => restwell_field( __( 'Checklist item 2 body', 'restwell-retreats' ), 'textarea' ),
			'home_care_note'      => restwell_field( __( 'Phone / contact note under the checklist', 'restwell-retreats' ) ),
			'home_care_cta_label' => restwell_field( __( 'Care link label', 'restwell-retreats' ) ),
			'home_care_cta_url'   => restwell_field( __( 'Care link URL (e.g. /optional-care/)', 'restwell-retreats' ) ),
		),
		'FAQ' => array(
			'home_faq_label'   => restwell_field( __( 'FAQ section eyebrow', 'restwell-retreats' ) ),
			'home_faq_heading' => restwell_field( __( 'FAQ section heading (h2). Answers come from the theme FAQ list, not these fields.', 'restwell-retreats' ) ),
		),
		'CTA' => array(
			'cta_heading'         => restwell_field( __( 'CTA heading (h2)', 'restwell-retreats' ) ),
			'cta_body'            => restwell_field( __( 'CTA body copy', 'restwell-retreats' ), 'textarea' ),
			'cta_primary_label'   => restwell_field( __( 'CTA primary button label', 'restwell-retreats' ) ),
			'cta_primary_url'     => restwell_field( __( 'CTA primary button URL', 'restwell-retreats' ) ),
			'cta_secondary_label' => restwell_field( __( 'CTA secondary button label', 'restwell-retreats' ) ),
			'cta_secondary_url'   => restwell_field( __( 'CTA secondary button URL', 'restwell-retreats' ) ),
			'cta_promise'         => restwell_field( __( 'CTA promise line (optional)', 'restwell-retreats' ) ),
			'cta_image_id'        => restwell_field( __( 'CTA background image (attachment ID)', 'restwell-retreats' ), 'image' ),
		),
	);
}

/**
 * The Property page.
 */
function restwell_get_property_field_definitions() {
	return array(
		'Address' => array(
			'prop_address_street'   => restwell_field( __( 'Street address (internal reference only; not used in public JSON-LD)', 'restwell-retreats' ) ),
			'prop_address_locality' => restwell_field( __( 'Town / city (internal reference only)', 'restwell-retreats' ) ),
			'prop_address_region'   => restwell_field( __( 'County / region (internal reference only)', 'restwell-retreats' ) ),
			'prop_address_postcode' => restwell_field( __( 'Postcode (internal reference only)', 'restwell-retreats' ) ),
		),
		'Hero' => array(
			'prop_hero_label'              => restwell_field( __( 'Hero label (e.g. The Property)', 'restwell-retreats' ) ),
			'prop_hero_heading'            => restwell_field( __( 'Hero heading (h1)', 'restwell-retreats' ) ),
			'prop_hero_subtitle'           => restwell_field( __( 'Hero subtitle (under heading)', 'restwell-retreats' ) ),
			'prop_hero_image_id'           => restwell_field( __( 'Hero image (attachment ID)', 'restwell-retreats' ), 'media' ),
			'prop_hero_cta_text'           => restwell_field( __( 'Hero primary CTA label (e.g. Ask about your dates)', 'restwell-retreats' ) ),
			'prop_hero_cta_url'            => restwell_field( __( 'Hero primary CTA URL', 'restwell-retreats' ) ),
			'prop_hero_cta_secondary_text' => restwell_field( __( 'Hero secondary CTA label (optional)', 'restwell-retreats' ) ),
			'prop_hero_cta_secondary_url'  => restwell_field( __( 'Hero secondary CTA URL (optional)', 'restwell-retreats' ) ),
			'prop_hero_cta_promise'        => restwell_field( __( 'Hero promise line (optional)', 'restwell-retreats' ) ),
		),
		'Home for the week' => array(
			'prop_bungalow_label'    => restwell_field( __( 'Overview section label (optional eyebrow)', 'restwell-retreats' ) ),
			'prop_bungalow_heading'  => restwell_field( __( 'Overview heading (h2)', 'restwell-retreats' ) ),
			'prop_bungalow_body'     => restwell_field( __( 'Overview body', 'restwell-retreats' ), 'textarea' ),
			'prop_bungalow_image_id' => restwell_field( __( 'Overview image (attachment ID, optional)', 'restwell-retreats' ), 'image' ),
		),
		'Room tour' => array(
			'prop_bedrooms_section_heading' => restwell_field( __( 'Bedrooms heading (h2 in tour)', 'restwell-retreats' ) ),
			'prop_bedrooms_section_body'    => restwell_field( __( 'Bedrooms body (paragraphs; blank line between)', 'restwell-retreats' ), 'textarea' ),
			'prop_tour_bedroom_image_id'    => restwell_field( __( 'Bedroom tour image (optional; falls back to gallery image 2)', 'restwell-retreats' ), 'image' ),
			'prop_wetroom_heading'          => restwell_field( __( 'Wet room heading (h2 in tour)', 'restwell-retreats' ) ),
			'prop_wetroom_body'             => restwell_field( __( 'Wet room body (paragraphs; blank line between)', 'restwell-retreats' ), 'textarea' ),
			'prop_tour_wetroom_image_id'    => restwell_field( __( 'Wet room tour image (optional; falls back to gallery image 3)', 'restwell-retreats' ), 'image' ),
			'prop_living_heading'           => restwell_field( __( 'Living room heading (h2 in tour)', 'restwell-retreats' ) ),
			'prop_living_body'              => restwell_field( __( 'Living room body (paragraphs; blank line between)', 'restwell-retreats' ), 'textarea' ),
			'prop_tour_living_image_id'     => restwell_field( __( 'Living tour image (optional; falls back to gallery image 1)', 'restwell-retreats' ), 'image' ),
			'prop_kitchen_heading'          => restwell_field( __( 'Kitchen heading (h2 in tour)', 'restwell-retreats' ) ),
			'prop_kitchen_body'             => restwell_field( __( 'Kitchen body (paragraphs; blank line between)', 'restwell-retreats' ), 'textarea' ),
			'prop_tour_kitchen_image_id'    => restwell_field( __( 'Kitchen tour image (optional; falls back to gallery match)', 'restwell-retreats' ), 'image' ),
			'prop_conservatory_heading'     => restwell_field( __( 'Conservatory heading (h2 in tour)', 'restwell-retreats' ) ),
			'prop_conservatory_body'        => restwell_field( __( 'Conservatory body (paragraphs; blank line between)', 'restwell-retreats' ), 'textarea' ),
			'prop_tour_conservatory_image_id' => restwell_field( __( 'Conservatory tour image (optional; falls back to gallery match)', 'restwell-retreats' ), 'image' ),
			'prop_garden_heading'           => restwell_field( __( 'Outside / garden heading (h2 in tour)', 'restwell-retreats' ) ),
			'prop_garden_body'              => restwell_field( __( 'Outside / garden body (paragraphs; blank line between)', 'restwell-retreats' ), 'textarea' ),
			'prop_tour_garden_image_id'     => restwell_field( __( 'Garden tour image (optional; falls back to gallery image 4)', 'restwell-retreats' ), 'image' ),
			'prop_throughout_heading'       => restwell_field( __( 'Access / throughout heading (h2 in tour)', 'restwell-retreats' ) ),
			'prop_throughout_body'          => restwell_field( __( 'Access / throughout body', 'restwell-retreats' ), 'textarea' ),
			'prop_tour_throughout_image_id' => restwell_field( __( 'Access tour image (optional; falls back to gallery match)', 'restwell-retreats' ), 'image' ),
		),
		'Care & location' => array(
			'prop_care_heading'     => restwell_field( __( 'Care section heading (h2)', 'restwell-retreats' ) ),
			'prop_care_body'        => restwell_field( __( 'Care section body', 'restwell-retreats' ), 'textarea' ),
			'prop_location_heading' => restwell_field( __( 'Location section heading (h2)', 'restwell-retreats' ) ),
			'prop_location_body'    => restwell_field( __( 'Location section body (paragraphs; blank line between)', 'restwell-retreats' ), 'textarea' ),
			'prop_location_image_id' => restwell_field( __( 'Location background photo (optional; frosted panel overlay)', 'restwell-retreats' ), 'image' ),
		),
		'Dignity' => array(
			'prop_dignity_label'    => restwell_field( __( 'Section label (eyebrow)', 'restwell-retreats' ) ),
			'prop_dignity_heading'  => restwell_field( __( 'Section heading (h2)', 'restwell-retreats' ) ),
			'prop_dignity_body'     => restwell_field( __( 'Body (paragraphs)', 'restwell-retreats' ), 'textarea' ),
			'prop_dignity_image_id' => restwell_field( __( 'Image (attachment ID)', 'restwell-retreats' ), 'image' ),
		),
		'Features' => array(
			'prop_features_label'   => restwell_field( __( 'Section label (eyebrow)', 'restwell-retreats' ) ),
			'prop_features_heading' => restwell_field( __( 'Section heading (h2)', 'restwell-retreats' ) ),
			'prop_feature_1'        => restwell_field( __( 'Feature 1 label', 'restwell-retreats' ) ),
			'prop_feature_1_desc'   => restwell_field( __( 'Feature 1 description', 'restwell-retreats' ), 'textarea' ),
			'prop_feature_2'        => restwell_field( __( 'Feature 2 label', 'restwell-retreats' ) ),
			'prop_feature_2_desc'   => restwell_field( __( 'Feature 2 description', 'restwell-retreats' ), 'textarea' ),
			'prop_feature_3'        => restwell_field( __( 'Feature 3 label', 'restwell-retreats' ) ),
			'prop_feature_3_desc'   => restwell_field( __( 'Feature 3 description', 'restwell-retreats' ), 'textarea' ),
			'prop_feature_4'        => restwell_field( __( 'Feature 4 label', 'restwell-retreats' ) ),
			'prop_feature_4_desc'   => restwell_field( __( 'Feature 4 description', 'restwell-retreats' ), 'textarea' ),
			'prop_feature_5'        => restwell_field( __( 'Feature 5 label', 'restwell-retreats' ) ),
			'prop_feature_5_desc'   => restwell_field( __( 'Feature 5 description', 'restwell-retreats' ), 'textarea' ),
			'prop_feature_6'        => restwell_field( __( 'Feature 6 label', 'restwell-retreats' ) ),
			'prop_feature_6_desc'   => restwell_field( __( 'Feature 6 description', 'restwell-retreats' ), 'textarea' ),
			'prop_feature_7'        => restwell_field( __( 'Feature 7 label', 'restwell-retreats' ) ),
			'prop_feature_7_desc'   => restwell_field( __( 'Feature 7 description', 'restwell-retreats' ), 'textarea' ),
			'prop_feature_8'        => restwell_field( __( 'Feature 8 label', 'restwell-retreats' ) ),
			'prop_feature_8_desc'   => restwell_field( __( 'Feature 8 description (optional)', 'restwell-retreats' ), 'textarea' ),
			'prop_glance_summary'   => restwell_field( __( 'At a glance summary paragraph', 'restwell-retreats' ), 'textarea' ),
		),
		'Overview' => array(
			'prop_overview_heading' => restwell_field( __( 'Overview heading (h2) - fallback for dignity', 'restwell-retreats' ) ),
			'prop_overview_body'    => restwell_field( __( 'Overview body (paragraphs)', 'restwell-retreats' ), 'textarea' ),
		),
		'Accessibility' => array(
			'prop_acc_label'     => restwell_field( __( 'Section label', 'restwell-retreats' ) ),
			'prop_acc_heading'   => restwell_field( __( 'Section heading (h2)', 'restwell-retreats' ) ),
			'prop_acc_intro'     => restwell_field( __( 'Intro paragraph', 'restwell-retreats' ), 'textarea' ),
			'prop_acc_confirmed' => restwell_field( __( 'Confirmed features (one per line)', 'restwell-retreats' ), 'textarea' ),
			'prop_acc_tbc'       => restwell_field( __( 'To be confirmed (one per line)', 'restwell-retreats' ), 'textarea' ),
		),
		'Comparison' => array(
			'prop_comparison_label'         => restwell_field( __( 'Section label (eyebrow)', 'restwell-retreats' ) ),
			'prop_comparison_heading'       => restwell_field( __( 'Section heading (h2)', 'restwell-retreats' ) ),
			'prop_comparison_intro'         => restwell_field( __( 'Intro paragraph', 'restwell-retreats' ), 'textarea' ),
			'prop_comparison_left_heading'  => restwell_field( __( 'Left column heading', 'restwell-retreats' ) ),
			'prop_comparison_right_heading' => restwell_field( __( 'Right column heading', 'restwell-retreats' ) ),
			'prop_comparison_left_1'        => restwell_field( __( 'Left bullet 1', 'restwell-retreats' ) ),
			'prop_comparison_left_2'        => restwell_field( __( 'Left bullet 2', 'restwell-retreats' ) ),
			'prop_comparison_left_3'        => restwell_field( __( 'Left bullet 3', 'restwell-retreats' ) ),
			'prop_comparison_left_4'        => restwell_field( __( 'Left bullet 4', 'restwell-retreats' ) ),
			'prop_comparison_right_1'       => restwell_field( __( 'Right bullet 1', 'restwell-retreats' ) ),
			'prop_comparison_right_2'       => restwell_field( __( 'Right bullet 2', 'restwell-retreats' ) ),
			'prop_comparison_right_3'       => restwell_field( __( 'Right bullet 3', 'restwell-retreats' ) ),
			'prop_comparison_right_4'       => restwell_field( __( 'Right bullet 4', 'restwell-retreats' ) ),
		),
		'Gallery' => array(
			'prop_gallery_label'       => restwell_field( __( 'Section label', 'restwell-retreats' ) ),
			'prop_gallery_heading'     => restwell_field( __( 'Section heading (h2)', 'restwell-retreats' ) ),
			'prop_gallery_image_ids'   => restwell_field( __( 'Gallery images (room-by-room; order preserved)', 'restwell-retreats' ), 'gallery' ),
			'prop_gallery_btn_1_label' => restwell_field( __( 'Button 1 label (e.g. Ask about your dates, or See all photos)', 'restwell-retreats' ) ),
			'prop_gallery_btn_1_url'   => restwell_field( __( 'Button 1 URL', 'restwell-retreats' ) ),
			'prop_gallery_btn_2_label' => restwell_field( __( 'Button 2 label (e.g. Explore video)', 'restwell-retreats' ) ),
			'prop_gallery_btn_2_url'   => restwell_field( __( 'Button 2 URL', 'restwell-retreats' ) ),
			'prop_gallery_btn_3_label' => restwell_field( __( 'Button 3 label (e.g. Take 3D Tour)', 'restwell-retreats' ) ),
			'prop_gallery_btn_3_url'   => restwell_field( __( 'Button 3 URL', 'restwell-retreats' ) ),
		),
		'Practical' => array(
			'prop_practical_label'     => restwell_field( __( 'Section label', 'restwell-retreats' ) ),
			'prop_practical_heading'   => restwell_field( __( 'Section heading (h2)', 'restwell-retreats' ) ),
			'prop_bedrooms_count'      => restwell_field( __( 'Bedrooms number (set only if verified)', 'restwell-retreats' ), 'number' ),
			'prop_bedrooms'            => restwell_field( __( 'Bedrooms text (fallback)', 'restwell-retreats' ) ),
			'prop_bathrooms_count'     => restwell_field( __( 'Bathrooms number (set only if verified)', 'restwell-retreats' ), 'number' ),
			'prop_bathroom'            => restwell_field( __( 'Bathroom text (fallback)', 'restwell-retreats' ) ),
			'prop_wetroom_walkthrough_url' => restwell_field( __( 'Wet room walkthrough URL (YouTube Shorts)', 'restwell-retreats' ) ),
			'prop_parking_label'       => restwell_field( __( 'Parking label (e.g. Parking)', 'restwell-retreats' ) ),
			'prop_parking'             => restwell_field( __( 'Parking count (e.g. 2)', 'restwell-retreats' ) ),
			'prop_parking_detail'      => restwell_field( __( 'Parking detail (e.g. Room for two vehicles on the resin-bound private drive)', 'restwell-retreats' ) ),
			'prop_sleeps_value'        => restwell_field( __( 'Sleeps value (set only if verified)', 'restwell-retreats' ), 'number' ),
			'prop_sleeps_label'        => restwell_field( __( 'Sleeps label (e.g. Sleeps)', 'restwell-retreats' ) ),
			'prop_distances'           => restwell_field( __( 'Distances text (fallback)', 'restwell-retreats' ) ),
			'prop_confirm_details_url' => restwell_field( __( 'Confirm details / gallery button fallback URL', 'restwell-retreats' ) ),
		),
		'Nearby' => array(
			'prop_nearby_label'      => restwell_field( __( 'Section label', 'restwell-retreats' ) ),
			'prop_nearby_heading'    => restwell_field( __( 'Section heading (h2)', 'restwell-retreats' ) ),
			'prop_nearby_1_title'    => restwell_field( __( 'Place 1 title', 'restwell-retreats' ) ),
			'prop_nearby_1_body'     => restwell_field( __( 'Place 1 body', 'restwell-retreats' ), 'textarea' ),
			'prop_nearby_1_acc'      => restwell_field( __( 'Place 1 accessibility note', 'restwell-retreats' ) ),
			'prop_nearby_1_distance' => restwell_field( __( 'Place 1 distance (e.g. Approx. 5 min walk)', 'restwell-retreats' ) ),
			'prop_nearby_1_filter'   => restwell_field( __( 'Place 1 filter: wheelchair-friendly, quieter, or practical', 'restwell-retreats' ) ),
			'prop_nearby_1_map_url'  => restwell_field( __( 'Place 1 Google Maps URL', 'restwell-retreats' ) ),
			'prop_nearby_2_title'    => restwell_field( __( 'Place 2 title', 'restwell-retreats' ) ),
			'prop_nearby_2_body'     => restwell_field( __( 'Place 2 body', 'restwell-retreats' ), 'textarea' ),
			'prop_nearby_2_acc'      => restwell_field( __( 'Place 2 accessibility note', 'restwell-retreats' ) ),
			'prop_nearby_2_distance' => restwell_field( __( 'Place 2 distance', 'restwell-retreats' ) ),
			'prop_nearby_2_filter'   => restwell_field( __( 'Place 2 filter', 'restwell-retreats' ) ),
			'prop_nearby_2_map_url'  => restwell_field( __( 'Place 2 Google Maps URL', 'restwell-retreats' ) ),
			'prop_nearby_3_title'    => restwell_field( __( 'Place 3 title', 'restwell-retreats' ) ),
			'prop_nearby_3_body'     => restwell_field( __( 'Place 3 body', 'restwell-retreats' ), 'textarea' ),
			'prop_nearby_3_acc'      => restwell_field( __( 'Place 3 accessibility note', 'restwell-retreats' ) ),
			'prop_nearby_3_distance' => restwell_field( __( 'Place 3 distance', 'restwell-retreats' ) ),
			'prop_nearby_3_filter'   => restwell_field( __( 'Place 3 filter', 'restwell-retreats' ) ),
			'prop_nearby_3_map_url'  => restwell_field( __( 'Place 3 Google Maps URL', 'restwell-retreats' ) ),
			'prop_nearby_4_title'    => restwell_field( __( 'Place 4 title', 'restwell-retreats' ) ),
			'prop_nearby_4_body'     => restwell_field( __( 'Place 4 body', 'restwell-retreats' ), 'textarea' ),
			'prop_nearby_4_acc'      => restwell_field( __( 'Place 4 accessibility note', 'restwell-retreats' ) ),
			'prop_nearby_4_distance' => restwell_field( __( 'Place 4 distance', 'restwell-retreats' ) ),
			'prop_nearby_4_filter'   => restwell_field( __( 'Place 4 filter', 'restwell-retreats' ) ),
			'prop_nearby_4_map_url'  => restwell_field( __( 'Place 4 Google Maps URL', 'restwell-retreats' ) ),
			'prop_nearby_5_title'    => restwell_field( __( 'Place 5 title (e.g. Supermarkets)', 'restwell-retreats' ) ),
			'prop_nearby_5_body'     => restwell_field( __( 'Place 5 body', 'restwell-retreats' ), 'textarea' ),
			'prop_nearby_5_acc'      => restwell_field( __( 'Place 5 accessibility note', 'restwell-retreats' ) ),
			'prop_nearby_5_distance' => restwell_field( __( 'Place 5 distance', 'restwell-retreats' ) ),
			'prop_nearby_5_filter'   => restwell_field( __( 'Place 5 filter', 'restwell-retreats' ) ),
			'prop_nearby_5_map_url'  => restwell_field( __( 'Place 5 Google Maps URL', 'restwell-retreats' ) ),
			'prop_nearby_6_title'    => restwell_field( __( 'Place 6 title (e.g. Local Pharmacies)', 'restwell-retreats' ) ),
			'prop_nearby_6_body'     => restwell_field( __( 'Place 6 body', 'restwell-retreats' ), 'textarea' ),
			'prop_nearby_6_acc'      => restwell_field( __( 'Place 6 accessibility note', 'restwell-retreats' ) ),
			'prop_nearby_6_distance' => restwell_field( __( 'Place 6 distance', 'restwell-retreats' ) ),
			'prop_nearby_6_filter'   => restwell_field( __( 'Place 6 filter', 'restwell-retreats' ) ),
			'prop_nearby_6_map_url'  => restwell_field( __( 'Place 6 Google Maps URL', 'restwell-retreats' ) ),
			'prop_nearby_7_title'    => restwell_field( __( 'Place 7 title (e.g. Getting Around)', 'restwell-retreats' ) ),
			'prop_nearby_7_body'     => restwell_field( __( 'Place 7 body', 'restwell-retreats' ), 'textarea' ),
			'prop_nearby_7_acc'      => restwell_field( __( 'Place 7 accessibility note', 'restwell-retreats' ) ),
			'prop_nearby_7_distance' => restwell_field( __( 'Place 7 distance', 'restwell-retreats' ) ),
			'prop_nearby_7_filter'   => restwell_field( __( 'Place 7 filter', 'restwell-retreats' ) ),
			'prop_nearby_7_map_url'  => restwell_field( __( 'Place 7 Google Maps URL', 'restwell-retreats' ) ),
			'prop_nearby_8_title'    => restwell_field( __( 'Place 8 title (e.g. Medical & Emergency)', 'restwell-retreats' ) ),
			'prop_nearby_8_body'     => restwell_field( __( 'Place 8 body', 'restwell-retreats' ), 'textarea' ),
			'prop_nearby_8_acc'      => restwell_field( __( 'Place 8 accessibility note', 'restwell-retreats' ) ),
			'prop_nearby_8_distance' => restwell_field( __( 'Place 8 distance', 'restwell-retreats' ) ),
			'prop_nearby_8_filter'   => restwell_field( __( 'Place 8 filter', 'restwell-retreats' ) ),
			'prop_nearby_8_map_url'  => restwell_field( __( 'Place 8 Google Maps URL', 'restwell-retreats' ) ),
			'prop_nearby_cta_label'  => restwell_field( __( 'Ninth card CTA label (e.g. Questions about access?)', 'restwell-retreats' ) ),
			'prop_nearby_cta_url'    => restwell_field( __( 'Ninth card CTA URL', 'restwell-retreats' ) ),
		),
		'CTA' => array(
			'prop_cta_heading' => restwell_field( __( 'CTA heading (h2)', 'restwell-retreats' ) ),
			'prop_cta_body'    => restwell_field( __( 'CTA body', 'restwell-retreats' ), 'textarea' ),
			'prop_cta_btn'     => restwell_field( __( 'Button label', 'restwell-retreats' ) ),
			'prop_cta_url'     => restwell_field( __( 'Button URL', 'restwell-retreats' ) ),
			'prop_cta_promise' => restwell_field( __( 'CTA promise line (optional)', 'restwell-retreats' ) ),
		),
	);
}
